### ISSUE TITLE
Result set size and paging

### ISSUE THREAD

**Issue by mustberuss** [CSSIP-AIR/PatentsView-APIWrapper#2]
A user in the[ patentsview forum](http://www.patentsview.org/community/forum/8/topic/114) asked why their config file produced fewer  results when their conditions were removed (*).  In looking at the wrapper code, it looks like it is only using the preview of 25 results and not attempting to page through the results set.  

I forked your repo and added code to address this though I don't have much experience with python.   I  have even less experience in making PRs and didn't know whether  an issue should be created before submitting a PR out of the blue.   What I added will request the api's maximum of 10,000 matches per request and will issue subsequent page requests as necessary. 

(*) The user's requests looked to be of different sizes since they asked for cpc_subgroup_id and received multiple rows per patent.  When this field was removed both requests generated only 25 rows.

**Comment by sarahkelley** [comment]
Thanks for point this out! Feel free to make a pull request and we will test it out and approve it (probably not until this next release cycle though).

Best, 

The PatentsView Team
